### ISSUE TITLE
Use ` canvas Error after todataurl ({format: 'image / PNG'}) `?

### ISSUE THREAD

**Issue by glk-hll** [guesant/fabricjs-object-fit#15]
After creating an object with 'objectfit', use 'canvas The following error occurred after todataurl ({format: 'image / PNG'}) `:
![image](https://user-images.githubusercontent.com/44257305/150744921-07661de1-1ef5-4ed0-8910-e49444ae7cf4.png)

It is normal to export pictures after creating objects with 'textbox'.

**Comment by guesant** [comment]
I think this bug is not related with fabricjs-object-fit.

You are using an image from some external server and adding it to your canvas, and you cannot export to a dataURL or blob without that server authorizing it (explicitly sending the header "allow-origin: [pattern that matches your app url]").

You can read more about it here (and maybe some workarounds):

- https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image
 
- https://stackoverflow.com/a/27840082/15515027
